### ISSUE TITLE
media lib - WHERE

### ISSUE THREAD

**Issue by adam4h** [yonglas-surfcode/MinhalFhill#16]
do it

**Comment by yonglas-surfcode** [comment]
there is no way to add custom field to the media lib fields 
i also didnt want to enter some value to the description field because this field can be usefull for the client.

so i decided to add number 1 for the codename.
that will control the gallery visibility.
![2015-02-11_1717](https://cloud.githubusercontent.com/assets/1401159/6149589/7395dd14-b212-11e4-8697-56320f2d0881.png)

and this is the where condition
![2015-02-11_1718](https://cloud.githubusercontent.com/assets/1401159/6149609/8f9e95fa-b212-11e4-928e-a272ac0ff243.png)
